version: "2"

linters:
  default: standard
  settings:
    staticcheck:
      checks:
        - all
        - -QF1003  # Don't suggest if/else -> switch conversions
        - -ST1003  # Don't enforce ID/URL naming conventions (pre-existing)
